Documentation: Fixed relative links
ynput/OpenPype pull request #2621
Opened 2022-02-01 17:13 UTC by m-u-r-p-h-y

## Brief description
some links in documentation are not generating correct links with relative syntax

## Changes
- changing relative links to point directly to corresponding md files

this way the links are not sensitive do endtrail slash "/" in URL address

2022-02-01 23:30 UTC, antirotor requested changes
Except those two dead links (that were dead even before) it works for me.

2022-02-01 23:30 UTC, antirotor commented on website/docs/artist_hosts_maya.md
> +* For setting up Deadline support see [here](admin_config.md#aws-thinkbox-deadline)
```suggestion
* For setting up Muster support see [admin section](module_muster.md)
* For setting up Deadline support see [here](module_deadline.md)
```

2022-02-02 09:48 UTC, mkolar approved these changes

2022-02-02 11:53 UTC, antirotor approved these changes

2022-02-07 15:39 UTC, merged