Blender: Extract Review
ynput/OpenPype pull request #3616
Opened 2022-08-04 10:24 UTC by simonebarbieri

## Brief description
Added Review to Blender.

## Description
This implementation is based on #3508 but made compatible for the current implementation of OpenPype for Blender.

2022-08-04 10:39 UTC, iLLiCiTiT commented on openpype/hosts/blender/plugins/publish/integrate_thumbnail.py
> +import pyblish.api
Import of other plugins is never a good idea. Why is this needed?

2022-10-14 07:41 UTC, LiborBatek approved these changes
Everything working fine...published model and review ok.
![image](https://user-images.githubusercontent.com/112623825/195790605-3fe6b4aa-b605-40ea-b891-95b73126d394.png)

2022-10-14 07:43 UTC, LiborBatek commented
Just a small note, the video doesnt have any burnins like maya one (author, version, date etc.) so not sure how it suppose to work in blender and/or how its created in...

2023-01-09 16:29 UTC, m-u-r-p-h-y commented
> Just a small note, the video doesnt have any burnins like maya one (author, version, date etc.) so not sure how it suppose to work in blender and/or how its created in...

It is done by a different plugin - Extract burnins

![image](https://user-images.githubusercontent.com/352795/211358093-6f9a7265-f23c-4922-84ae-710444555685.png)

2023-01-10 08:00 UTC, mkolar requested changes
There's a syntax error in the default blender settings. That means that you probably created the defaults manually rather than using the developer mode in the settings GUI. Please use it every time you create a new settings to prevent this from happening. 
![image](https://user-images.githubusercontent.com/3333008/211493997-75f460ec-bf6f-415e-ae70-de2b5a46a4a0.png)

Secondly, it looks like you still have OCIO configs submodule in your branch, however, it was removed in the upstream and this PR is trying to get it back. Please remove it before we merge this.

2023-01-13 10:23 UTC, iLLiCiTiT commented on openpype/hosts/blender/plugins/publish/extract_thumbnail.py
> +
```suggestion
    order = pyblish.api.ExtractorOrder + 0.01
    presets = {}
```

2023-01-13 10:24 UTC, iLLiCiTiT commented on openpype/hosts/blender/plugins/publish/extract_thumbnail.py
> +        preset = presets.get(family, {})
```suggestion
        preset = self.presets.get(family, {})
```

2023-01-19 10:14 UTC, iLLiCiTiT commented on openpype/hosts/blender/plugins/publish/extract_playblast.py
> +        print(instance.context.data)
```suggestion
```

2023-01-19 10:14 UTC, iLLiCiTiT commented on openpype/hosts/blender/plugins/publish/extract_thumbnail.py
> +import openpype.api
Please don't use `openpype.api` anymore.

2023-03-17 13:14 UTC, antirotor approved these changes

2023-03-17 13:15 UTC, merged