Maya: Rendersettings unify logic towards single library
ynput/OpenPype pull request #3880
Opened 2022-09-17 13:14 UTC by BigRoy

## Brief description

This tries to reduce the scattered hardcoded values for renderer attribute names, types and tries to clean up the same things on the `RenderSettings` class. I've also refactored the usage of it across the code.

## Description

- Delays getting image prefixes per renderer instead of loading project settings three times on import of `lib_rendersettings`
- Move over missing image prefixes values that existed on validator but not in `lib_rendersettings`
- Move over AOV char logic to `lib_rendersettings`
- Readability cosmetic tweaks on some lines which did more complex formatting than needed.
- Removed `lib.RENDER_ATTRS` in favor of the now added `RenderSettings.get_padding_attr` (other logic of `lib.RENDER_ATTRS` was unused)

## Additional info

Relates to #3878, #3879 and #3821 since they touch a similar area of the codebase.
Also relates to #3873 which also touches an aspect of rendering in Maya.

## Testing notes:
1. Test creation, validating and publishing of Render instances.
2. Ensure "Reset render settings" works as expected.

2022-09-18 12:00 UTC, BigRoy commented
@mkolar @antirotor what do we think of adding this https://github.com/BigRoy/OpenPype/pull/7 to `RenderSettings` as well?

2022-09-19 16:22 UTC, antirotor commented
> @mkolar @antirotor what do we think of adding this [BigRoy#7](https://github.com/BigRoy/OpenPype/pull/7) to `RenderSettings` as well?

Yes please!

2022-09-20 07:07 UTC, LiborBatek commented
I ve done the testing and it gives error when validating the scene during pyblish same as in #3884 
![image](https://user-images.githubusercontent.com/112623825/191189969-2d433ec4-fc9d-451c-9295-11689191e85b.png)

so I guess the preset should be resolved first and test this PR later then...

2022-09-20 07:59 UTC, BigRoy commented
Oh - this is **so close!** Because note how it does recommend a prefix without the `<RenderPass>` as the end but unfortunately it has a trailing underscore. And that's because this particular PR does not contain the preset fix from #3884. Let me resolve that quickly.

2022-09-20 08:42 UTC, BigRoy commented
Ok, I have changed the default prefix for Arnold. I've also added an error log for when Render Settings get applied and the Multilayer EXR does not match the Image Prefix.

And have also added a label to the Settings UI so it's mentioned to the user that the Image Prefix should contain both `{aov_separator}` and `<RenderPass>` when `Multilayer EXR` is disabled. It looks like this:

![afbeelding](https://user-images.githubusercontent.com/2439881/191210834-67041ccf-f516-427d-8e85-896a2ae253b3.png)

@LiborBatek - I expect the default settings to now pass.

2022-09-21 07:21 UTC, LiborBatek commented
Tested it out, I have freshly created "renderMain" family and runned Publish. Also applied OP>Set Render Settings before publish.

Still gives me these errors when validating...
![image](https://user-images.githubusercontent.com/112623825/191439646-72b15fee-d3bf-4875-add4-8c268cb648e9.png)

if I change Name Prefix to ....   "maya/<Scene>/<RenderLayer>/<RenderLayer>"

it just gives me this Warning msg but Publish can be triggered.
![image](https://user-images.githubusercontent.com/112623825/191440338-1918d456-bf8b-4ab5-bddc-74922403a395.png)

2022-09-22 08:47 UTC, BigRoy commented
Thanks @LiborBatek - I've tested on my end and it consistently seems to work.

I have tested:
```json
"project_settings/maya/RenderSettings/arnold_renderer/image_prefix":
    "maya/<Scene>/<RenderLayer>/<RenderLayer>{aov_separator}<RenderPass>"
"project_settings/maya/RenderSettings/arnold_renderer/multilayer_exr":
    false
```

```json
"project_settings/maya/RenderSettings/arnold_renderer/image_prefix":
    "maya/<Scene>/<RenderLayer>/<RenderLayer>"
"project_settings/maya/RenderSettings/arnold_renderer/multilayer_exr":
    true
```

Resetting the render settings works fine. Validating works fine.

It looks instead like your settings currently have an override compared to the default and `{aov_separator}` is not present.
So likely you image prefix was set to but you had multipart enabled:
```
maya/<Scene>/<RenderLayer>/<RenderLayer>_<RenderPass>
```

---

Anyway, I have made some news commits and tweaked the validations now so that hopefully you'll get a clearer response as to what it's validating against from settings. It will now just report if your prefix mismatches what is defined in settings.

Also, with your specific settings it sounds like you should have had a logged warning on Set Render Settings as well.

2022-09-22 14:40 UTC, LiborBatek commented
@BigRoy sorry but seems its not working correctly. 

here are my OP project settings:
![image](https://user-images.githubusercontent.com/112623825/191776561-4b4339b1-47a5-43f9-88c7-3a9ba860b461.png)

and here my publish error I get:

![image](https://user-images.githubusercontent.com/112623825/191776972-c80d89c4-fa1f-4463-9ef1-80a6087261bd.png)

this msg ```You must have: '<renderpass>' token with merge AOVs turned off``` seems to be off because I clearly have this token in my name prefix as seen on the second scrnshot.

Thanks

2022-09-22 15:45 UTC, BigRoy commented
> this msg You must have: '<renderpass>' token with merge AOVs turned off seems to be off because I clearly have this token in my name prefix as seen on the second scrnshot.

I'm so sorry for wasting so much of your time @LiborBatek. I [accidentally changed the `if not prefix_has_aov_token` statement to `if prefix_has_aov_token`](https://github.com/pypeclub/OpenPype/pull/3880/commits/7818766e5e25742618cc6052edaaa460d3096d39) for that scenario. It's fixed with [this commit](https://github.com/pypeclub/OpenPype/pull/3880/commits/054eead045d9ba62f1420fb16589f8e41042bf44).

Thanks so much for the continuous checks and following up with screenshots and details.

2022-09-23 07:02 UTC, LiborBatek commented
@BigRoy No problem at all! You do wondreful job man! We are humans after all no worries!

Thanks for your effort too!!

Cheers
L.

2022-09-23 08:06 UTC, LiborBatek commented
It has been all tested and works fine now. However Im not able to give it "Review". @antirotor 

Thx @BigRoy

2022-09-23 08:09 UTC, Allan-I commented
I'll give this a review in a bit let me just grab some coffee.

2022-09-23 11:25 UTC, BigRoy commented
I've resolved the merge conflicts just now.

2022-10-06 21:42 UTC, BigRoy commented
@Allan-I what's the status on this one?

2022-11-08 15:23 UTC, LiborBatek commented
I have tested it in ```maya2022``` with ```Redshift 3.0.67``` and it doesnt work besides image prefix which is ok the rest of settings is not taken into account, also any AOVs set in OP render settings are ignored (could be the RS version difference tho)

these are my OP settings for RS:
![image](https://user-images.githubusercontent.com/112623825/200603850-7efe2e1e-0968-4aee-94c7-3e96c0576ce1.png)

and maya render settings after applying OP render settings:
![image](https://user-images.githubusercontent.com/112623825/200604745-8b3834d0-4e16-4f79-93b6-5b3b0de5bfad.png)

2022-12-02 12:59 UTC, LiborBatek requested changes
Doesnt work yet, See latest comments. thx

2023-04-03 08:30 UTC, BigRoy commented
I've tried to merge with latest develop and resolve the conflicts. It was quite a beast to resolve but I think it's ok.
Just wondering whether we still find this PR worth the changes.

It contains some changes to areas of code similar to the following PRs:
- #4375 
- #4723 - note: this PR is targeted to `release/next-minor` - specifically the cleanup of getting the 'project_settings' for the render settings.
 
And thus it might end up generating merge conflicts with those too. It might be worth waiting for those PRs to be merged to resolve conflicts here once more and _then_ get to testing to avoid having to test numerous times.

2023-04-06 07:47 UTC, tokejepsen requested changes
Tested successfully in Maya 2023.

Think we need some checkboxes in the description to tick off the renderers tested.

2023-04-06 09:56 UTC, BigRoy commented
> Think we need some checkboxes in the description to tick off the renderers tested.

Added [here](https://github.com/ynput/OpenPype/pull/3880#issue-1376769746).

2023-04-06 09:57 UTC, BigRoy commented on openpype/hosts/maya/api/lib_rendersettings.py
> +        'mentalray': 'defaultRenderGlobals.imageFilePrefix',
True story, I'll remove it since it wasn't there anyway - not sure where this came from. (Maybe it was there a long time ago?)

2023-04-06 10:39 UTC, tokejepsen requested changes
If you have `Merge AOV` disabled and remove the token <RenderPass>, the validate/repair never gets it back. This is for Maya and Arnold.

Tested in Maya 2020 successfully with #4795 merged.

2023-04-06 12:20 UTC, BigRoy commented
> If you have Merge AOV disabled and remove the token , the validate/repair never gets it back. This is for Maya and Arnold.

Could you elaborate the preferred behavior. The question is what "repair" should do or allow? If I understand correctly it should revert the merge AOV option back to what the settings dictate, correct? It's not up to the scene or artist to deviate from the merge AOV option, yes?

Currently the validation DOES allow to deviate merge AOVs settings + the image prefix as well. Which maybe makes it weird if it then forces the value on repair if it invalidates based on another setting?

The validator does require however the token to match with the merge AOV setting, so have `<renderpass> if merge AOV is disabled, and not have <renderpass> if it's enabled.

Anyway, I've now made it so that it also repairs the merge AOV setting. @tokejepsen does that solve it for you?

2023-04-06 13:43 UTC, tokejepsen commented
> Could you elaborate the preferred behavior. The question is what "repair" should do or allow? 

I think the repair should fix the file name prefix according to what state the `Merge AOVs` is in.

`Merge AOVs` enabled > no `<RenderPass>` token.
`Merge AOVs` disabled > need `<RenderPass>` token.

2023-04-06 13:44 UTC, tokejepsen commented
Also Maya Hardware 2.0 works.

2023-04-06 13:52 UTC, BigRoy commented
> I think the repair should fix the file name prefix according to what state the Merge AOVs is in.

> Merge AOVs enabled > no <RenderPass> token.
> Merge AOVs disabled > need <RenderPass> token.

What should happen if the default prefix in settings does NOT have a <RenderPass> token, should we append it to the end?

2023-04-10 08:32 UTC, tokejepsen approved these changes
Code looks good and partially tested for the renderers I can.

2023-04-13 00:54 UTC, moonyuet commented
> @LiborBatek could you test again whether in the meantime your issue mentioned [here](https://github.com/ynput/OpenPype/pull/3880#issuecomment-1323300252) has been resolved?
> 
> There have been changes in code (4 months ago) by @moonyuet [here](https://github.com/ynput/OpenPype/blame/08354f512dda197fa7c00539748ee2fc0cb18d10/openpype/hosts/maya/api/lib_rendersettings.py#L252-L267) which I'm not sure whether they do what it intends to do. Since it seems off that first it's trying to set `redshiftOptions.primaryGIEngine` and `redshiftOptions.secondaryGIEngine` based on some conditions but in the end it still ALWAYS sets it to the value `int(rs_p_engine)` and `int(rs_s_engine)`. Seems like a bug @moonyuet ?
> 
> Anyway, the code seems related to the issue you described @LiborBatek so I suspect your particular issue has been resolved.

maybe needs a double check on the particular setting, the related PR is https://github.com/ynput/OpenPype/pull/4087

2023-04-14 15:14 UTC, LiborBatek requested changes
Did test in Vray and got error when triggered ```Repair``` on Render Settings (I have left intentionally empty ```File Name Prefix``` empty)

![image](https://user-images.githubusercontent.com/112623825/232084377-47f068bd-ed3b-4ce1-8c91-5df1b9381a1d.png)

2023-07-25 07:30 UTC, tokejepsen commented
@BigRoy could you resolve the conflicts?

2023-10-20 09:32 UTC, BigRoy commented
> maybe silly question, how this PR adhere to the new publisher in maya? all good?!

I don't expect it to be functional momentarily - it's a very old PR that I'm not sure how to best merge logically nowadays. I think we might have it merged in our colorbleed branch and along the way have synced that branch with new publisher - etc. but likely that's seen decent refactoring to make it work.

However, some of the cleanup is still relevant - I'll close this PR and see if I can set up a new one with some of the cleanup in here that is still relevant.

2023-10-20 09:32 UTC, closed without merging