Maya: fix rounding of fps
ynput/OpenPype pull request #4076
Opened 2022-11-07 17:56 UTC by antirotor

## Bug

This is fixing problem when fps is defined in greater precision than Maya is expecting (for example when it is defined as `23.9760246277` in db and Maya logic is expecting `23.98`)

Close #2620

2022-11-10 08:19 UTC, m-u-r-p-h-y reviewed
In my case, everything seems correct.

- project set to 29.97 in ftrack and synced to avalon
- created shot in ftrack and synced to avalon
- manually changed the shot fps to `23.9760246277` in mongoDB
- started Maya (2022) and created animation instance with some content (Maya starts with 25fps by default)
- run publish and used automatic repair on Maya Unit validator. fps changed from 25fps to 23.967 in Maya
- run publish again
- everything is OK


<img width="1171" alt="image" src="https://user-images.githubusercontent.com/352795/201035993-c90326c3-0c64-42a8-946f-b3c01ae49d5a.png">


so it seems it is fixing the issue of higher precision number in mongoDB (coming from hiero editorial for example)
but rounding not working in @LiborBatek case

2022-11-10 08:20 UTC, m-u-r-p-h-y commented
btw, should we fix project manager to show full length number for fps for better diagnostics?

2022-11-10 10:17 UTC, m-u-r-p-h-y requested changes
just created another shot to confirm Libor's case and it is not handled correctly definitely

did not touch mongoDB, just let the ftrack sync to avalon

during the workfile save there is a warning about fps mismatch (we should use floats to see the issue properly)

<img width="337" alt="image" src="https://user-images.githubusercontent.com/352795/201058322-c5f15644-79d4-4beb-8969-5d3ae096733c.png">
 

after fixing the scene, the Units validator fails, as there is double rounding happening apparently

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/352795/201064441-4be9d26f-988d-4695-ad20-3896f79b3b90.png">

2022-11-11 17:38 UTC, antirotor commented
> after fixing the scene, the Units validator fails, as there is double rounding happening apparently

I don't think it is because of double rounding - it all stems from ftrack handling of decimal places. In ftrack, it will be **29.97**, but since maya stores it in much higher precision, it will correctly ceil the value to 29.98, because `ceil(29.968)` is **29.98**.

Since we are not able to tell during validation if that fps value in mongo is set by ftrack that is flooring the value, or it is set by any other means where the ceil is the rounding method, I am not really sure how to handle it except storing fps value as string on ftrack, or adding logic trying to guess if ftrack module is enabled...

2022-11-21 16:25 UTC, antirotor commented
I hope I've fixed it by comparing only numbers with the same precision.

2022-11-24 09:56 UTC, LiborBatek commented
So I ve made the test...

first setting the fps to 23.976024 in MongoDB also checked Project Manager to see if set accordingly...
![PR#4076_scrnsht01](https://user-images.githubusercontent.com/112623825/203752855-77033a36-a598-4436-82cd-8b1d4cbeef29.jpg)

then I ve opened the shot and Maya told me to fix keyframes (I didnt go for fix and ignored it)
![PR#4076_scrnsht01C](https://user-images.githubusercontent.com/112623825/203753068-5aa4078c-1932-4c59-946e-06341dd9be0a.jpg)
afterwards went for shot publish and got this error with wrong FPS set in the scene (also note small issue with incorrect info about actual fps seems rounded already but still being that 23.976)
![PR#4076_scrnsht01B](https://user-images.githubusercontent.com/112623825/203753436-a19aa9f2-615d-4d47-8f66-438493066cf7.jpg)

When triggered Repair action all went good and shot was set to exact FPS 23.976 and Publish went ok! see maya fps in timeline...

![PR#4076_scrnsht02](https://user-images.githubusercontent.com/112623825/203753679-a687174e-a748-4091-87c9-5f9b902caedc.jpg)

Seem fine to me besides small desinformation regarding 24fps instead of 23.976 in info/warning message.

2022-11-25 15:46 UTC, m-u-r-p-h-y commented
My testing scenario is (M2022)

sh001

set to `29.97` in mongoDB

<img width="270" alt="image" src="https://user-images.githubusercontent.com/352795/204016518-95d97d5a-2caf-4895-a109-addd6ba457dd.png">


opening sh001 workfile with fps set to 25fps

`currentUnit -l centimeter -a degree -t pal;`


which brings the popup message to fix the fps on file open

<img width="340" alt="image" src="https://user-images.githubusercontent.com/352795/204017207-06118a84-d9a7-42e3-a911-36d6b46e9235.png">

with sill not very precise message about project fps of 29 fps 


after pressing fix, OP is changing the scene fps:

`// openpype.hosts.maya.api.lib : Setting scene FPS to: '29.97fps' // `


but Maya Units validation is not passing

<img width="330" alt="image" src="https://user-images.githubusercontent.com/352795/204018019-76c37e70-79f6-4f46-aa2e-961016390e11.png">

Repair function on the validator is not helping either, even though it says

`// openpype.hosts.maya.api.lib : Setting scene FPS to: '29.97fps' // `

but the validation fails with the above message again

2022-11-28 07:47 UTC, LiborBatek commented
To me it seems that Maya Fix FPS causes that weird FPS value...

Did u tried to not trigger that maya fix FPS? It could be it also it doesnt mean user wants to fix keyframe by moving them on the timeline to match new FPS but keep them as they are...

2022-12-01 14:00 UTC, m-u-r-p-h-y commented
> To me it seems that Maya Fix FPS causes that weird FPS value...
> 
> Did u tried to not trigger that maya fix FPS? It could be it also it doesnt mean user wants to fix keyframe by moving them on the timeline to match new FPS but keep them as they are...

user has to toggle the switch to modyfi the keyframes. The fix is only changing the scene fps by default.

2023-02-16 22:42 UTC, antirotor commented
solved by #4424

2023-02-16 22:42 UTC, closed without merging