General: Legacy io not used in global plugins
ynput/OpenPype pull request #4134
Opened 2022-11-24 10:00 UTC by iLLiCiTiT

## Brief description
Session data from `legacy_io` are not used in most of global plugins.

## Description
Usage of `legacy_io.Session` was replaced with using data stored on pyblish context. Some plugins are still using legacy io but those plugins already have opened PR changing them or replacement in them would need more overall changes.

## Additional information
Replacement usage of session keys stored in context.data:
- `"AVALON_APP"` -> `"hostName"`
- `"AVALON_PROJECT"` -> `"projectName"`
- `"AVALON_ASSET"` -> `"asset"`
- `"AVALON_TASK"` -> `"task"`

## Testing notes:
- [ ] Farm cleanup plugin is working
- [ ] Collect anatomy instance data has right project locally and on farm
- [ ] Collect scene loaded versions  has right project locally and on farm
- [ ] Integrate is integrating to right project locally and on farm
- [ ] Validate editorial asset is validating correctly

2022-12-19 12:53 UTC, kalisp requested changes
In AE it fails locally with 
![2022-12-19 13_52_25-Testing Platform PC - AnyDesk](https://user-images.githubusercontent.com/4457962/208430601-73b18c3c-d890-42bd-9267-9a507b18324c.png)

(It probably fails also in PS, Maya and Nuke - in automatic tests)

2022-12-19 13:13 UTC, iLLiCiTiT commented on openpype/plugins/publish/integrate.py
> +        project_name = instance.context["projectName"]
```suggestion
        project_name = instance.context.data["projectName"]
```

2022-12-19 13:13 UTC, iLLiCiTiT commented
> In AE it fails locally with

Should be fixed now.

2022-12-19 20:55 UTC, jakubjezek001 approved these changes
Tested only Validate Editorial asset name and it worked

2023-01-09 12:54 UTC, antirotor approved these changes
tested in maya and it works

2023-01-09 17:07 UTC, merged