Maya: Fix validate frame range repair + fix create render with deadline disabled
ynput/OpenPype pull request #4279
Opened 2023-01-04 14:40 UTC by BigRoy

## Brief description

This fixes:
- #4272 - Now handles are set as expected if `handleStart` and `handleEnd` attribute exists on the instance
- #3302 - Render Layer frame ranges are now also repaired - also works with explicit render layer overrides on a layer
- Create Render globals not working (errors) when Deadline module is disabled

## Testing notes:

1. Test Create Render with Deadline module disabled and with it enabled in a scene that **does not yet** have a `renderingMain` globals.
2. Check with different start+end frame + handles settings for an asset on renderlayers, but also on other instances like pointcaches and cameras.

2023-01-05 12:18 UTC, LiborBatek commented
Did a first rum of test with creating ```Render``` subset. 

It works ok when deadline is turned on (deadlinewebservice is running) but gives errors when deadline module is off in OP settings and not running...

![image](https://user-images.githubusercontent.com/112623825/210778451-7c095347-6160-4d1b-b4f4-a4277a8cb6b6.png)

will send soon testing for the rest (Step - 02)

2023-01-05 13:29 UTC, LiborBatek commented
Test 02 - different frame start / end + frame handles setting and ```repair``` action

The ```repair``` action works on subsets (camera, review, animation etc) but it just set ```frame start``` and ```frame end``` according to absolute frame range as in DB (range + handles together) which sort of works but it doesnt respect the handle values in DB and the repair action doesnt put these values in. It behaves as in this PR #4272 aka same issue. So question is:
is it desirable to maintain frame start/end and frame handle start/end values exactly (as in DB) or just we care about absolute frame range so they match overall (maya scene / DB)

Another issue with ```repair``` action is when used on ```renderLayer``` and frame range overrides...it just fails and gives this error msg:
![image](https://user-images.githubusercontent.com/112623825/210791184-4ef21387-58bf-4fc7-b41e-953a1762661e.png)

2023-01-05 13:30 UTC, LiborBatek requested changes
Pls see comments, needs change doesnt work as expected.

2023-01-05 14:00 UTC, BigRoy commented
@LiborBatek I'm pretty sure you were NOT running those tests on the code in this PR but were running it on a different branch. The line numbers in the error of your first screenshot [here](https://github.com/ynput/OpenPype/pull/4279#issuecomment-1372146125) refer to very different lines in this PR. 

Also the second test you've done is exactly what this PR should also solve. Are you sure you tested correctly?

2023-01-05 14:33 UTC, LiborBatek approved these changes
All works as expected. Creating ```render``` subset in any circumstances (with/without deadline running). 
Repair action aslo works on all subsets and renderlayers as expected. Also sets correctly handle start and handle end. So it also resolves PR #4272

Here is scrncap before repair:
![image](https://user-images.githubusercontent.com/112623825/210803783-f4b4f72c-b260-4f79-9ec5-aea995c4b00c.png)

and after:

![image](https://user-images.githubusercontent.com/112623825/210803886-ce6b174c-f760-4770-8bfa-b89545df0749.png)

here is also DB values for check and all is ok...frame ranges are equal and handles set correctly in maya.
![image](https://user-images.githubusercontent.com/112623825/210804099-b8088d75-d21e-4a82-8c28-a3f40a9e15a5.png)

2023-01-06 22:29 UTC, antirotor approved these changes

2023-01-06 22:29 UTC, merged