Fix - addSite loader handles hero version
ynput/OpenPype pull request #4359
Opened 2023-01-20 18:42 UTC by kalisp

## Brief description
If adding site to representation presence of hero version is checked, if found hero version is marked to be donwloaded too.

## Testing notes:
1. locate subset which has some hero version in Loader
2.use latest version of said subset and `Download` representation (in right bottom)
3. check that both latest and hero version representation were downloaded

2023-01-24 08:19 UTC, Tilix4 commented
Works fine, thanks!

2023-01-24 08:27 UTC, Tilix4 approved these changes
Works well! Thanks!

2023-01-24 08:27 UTC, Tilix4 commented on openpype/plugins/load/add_site.py
> +
Missing params in docstring

2023-01-24 14:47 UTC, Tilix4 requested changes
My bad, it doesn't work when subset are added to queue as input dependencies!

2023-01-25 17:27 UTC, kalisp commented
Updated handling of hero version.

2023-01-26 08:16 UTC, Tilix4 commented
Works better for dependencies! but it doesn't fetch dependencies which also have their own dependencies. In the screenshot provided, the two missing ones are not atomic dependencies when the fetched ones have no inputs.
![image](https://user-images.githubusercontent.com/22875539/214787316-ec4028c2-2dc3-4010-a93d-e39872f8b2cc.png)

2023-02-08 12:49 UTC, Tilix4 approved these changes
LGTM now! Thanks

2023-02-09 10:57 UTC, Tilix4 approved these changes
Tested :ok: ! LGTM

2023-02-09 12:10 UTC, iLLiCiTiT commented on openpype/plugins/load/add_site.py
> +    def _add_hero_representation_ids(self, project_name, repre_id):
Unused method

2023-02-10 15:26 UTC, iLLiCiTiT approved these changes

2023-02-10 15:27 UTC, merged