Refactored Generation of UE Projects, installation of plugins moved to the engine
ynput/OpenPype pull request #4369
Opened 2023-01-25 10:50 UTC by Casgen

## Brief description
Improved the way how OpenPype works with generation of UE projects. Also the installation of the plugin has been altered to install into the engine

## Description
OpenPype now uses the appropriate tools to generate UE projects. Unreal Build Tool (UBT) and a "Commandlet Project" is needed to properly generate a BP project, or C++ code in case that `dev_mode = True`, folders, the .uproject file and many other resources.

On the plugin's side, it is built seperately with the UnrealAutomationTool (UAT) and then it's contents are moved under the `Engine/Plugins/Marketplace/OpenPype` directory.

## Additional info
Note that `AssetContainer` and `AssetContainerFactory` C++ **code has been removed**, since it is not used. It will also help to comply with the guidelines of the marketplace plugins, which implies that no unsused code should be present in the source code.

## Testing notes:

### Installation of the plugin and creation of the project

1. Open OpenPype
2. Create a new Project through the Project Manager in the Admin section
3. Open up the Launcher
4. Launch the project with Unreal Engine 5.0 or 4.27 (You'll might need specify beforehand that it will use Unreal Engine as an application in the Project Settings)
5. The plugin should be installing and project generation should be running
6. If the process is successful, the project should normally load and run.

2023-01-25 10:50 UTC, jakubjezek001 commented
Task linked: [OP-3751 Unreal: add OpenPype plugin to Marketplace](https://app.clickup.com/t/6658547/OP-3751)

2023-01-31 10:08 UTC, simonebarbieri requested changes
I'm getting this error with both 4.27 and 5.0:
```
ERROR: Plugin 'C:\Dev\OpenPype\openpype\openpype\hosts\unreal\integration\UE_4.7\OpenPype.uplugin' not found
       (see C:\Users\Simone\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.27\Log.txt for full exception trace)
AutomationTool exiting with ExitCode=1 (Error_Unknown)
BUILD FAILED
WARNING:openpype.tools.launcher.window.LauncherWindow:Action launch failed.
Traceback (most recent call last):
  File "C:\Dev\OpenPype\openpype\openpype\tools\launcher\window.py", line 411, in run_action
    action().process(filtered_session)
  File "C:\Dev\OpenPype\openpype\openpype\tools\launcher\actions.py", line 116, in process
    **self.data
  File "C:\Dev\OpenPype\openpype\openpype\lib\applications.py", line 363, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "C:\Dev\OpenPype\openpype\openpype\lib\applications.py", line 516, in launch
    return context.launch()
  File "C:\Dev\OpenPype\openpype\openpype\lib\applications.py", line 1235, in launch
    prelaunch_hook.execute()
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\hooks\pre_workfile_preparation.py", line 141, in execute
    unreal_lib.try_installing_plugin(Path(engine_path), engine_version)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\lib.py", line 380, in try_installing_plugin
    _build_and_move_plugin(engine_path, op_plugin_path, env)
  File "C:\Dev\OpenPype\openpype\openpype\hosts\unreal\lib.py", line 414, in _build_and_move_plugin
    plugin_install_config_path.as_posix())
  File "C:\Dev\OpenPype\openpype\.venv\lib\site-packages\setuptools\_distutils\dir_util.py", line 124, in copy_tree
    "cannot copy tree '%s': not a directory" % src)
distutils.errors.DistutilsFileError: cannot copy tree 'C:/Dev/OpenPype/openpype/openpype/hosts/unreal/integration/UE_4.7/Config': not a directory
```

The path for the Unreal project is missing an `\OpenPype` (it should be `openpype\hosts\unreal\integration\UE_4.7\OpenPype\OpenPype.uplugin`)!

2023-02-17 17:41 UTC, antirotor commented
It can't create the project for me. Detailed traceback here:

<details>
<summary>Traceback:</summary>

```python
[2023.02.17-17.03.58:723][  0]LogInit: Error: OPGenerateProjecCommandlet looked like a commandlet, but we could not find the class.
[2023.02.17-17.03.59:033][  0]LogShaderCompilers: Display: ================================================
[2023.02.17-17.03.59:033][  0]LogShaderCompilers: Display: === FShaderJobCache stats ===
[2023.02.17-17.03.59:033][  0]LogShaderCompilers: Display: Total job queries 0, among them cache hits 0 (0.00%)
[2023.02.17-17.03.59:033][  0]LogShaderCompilers: Display: Tracking 0 distinct input hashes that result in 0 distinct outputs (0.00%)
[2023.02.17-17.03.59:033][  0]LogShaderCompilers: Display: RAM used: 0.00 MB (0.00 GB) of 819.20 MB (0.80 GB) budget. Usage: 0.00%
[2023.02.17-17.03.59:034][  0]LogShaderCompilers: Display: === Shader Compilation stats ===
[2023.02.17-17.03.59:034][  0]LogShaderCompilers: Display: Shaders Compiled: 0
[2023.02.17-17.03.59:034][  0]LogShaderCompilers: Display: Jobs assigned 0, completed 0 (0.00%)
[2023.02.17-17.03.59:034][  0]LogShaderCompilers: Display: Time at least one job was in flight (either pending or executed): 0.00 s
[2023.02.17-17.03.59:034][  0]LogShaderCompilers: Display: ================================================
[2023.02.17-17.03.59:116][  0]LogShaderCompilers: Display: Shaders left to compile 0
WARNING:openpype.tools.launcher.window.LauncherWindow:Action launch failed.
Traceback (most recent call last):
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\tools\launcher\window.py", line 411, in run_action
    action().process(filtered_session)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\tools\launcher\actions.py", line 112, in process
    self.application.launch(
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\lib\applications.py", line 363, in launch
    return self.manager.launch(self.full_name, *args, **kwargs)
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\lib\applications.py", line 516, in launch
    return context.launch()
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\lib\applications.py", line 1236, in launch
    prelaunch_hook.execute()
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\hosts\unreal\hooks\pre_workfile_preparation.py", line 150, in execute
    unreal_lib.create_unreal_project(
  File "C:\Users\annat\Documents\Projects\OpenPype\sources\op-py39\openpype\hosts\unreal\lib.py", line 248, in create_unreal_project
    raise RuntimeError(f'Failed to generate \'{project_name}\' project! '
RuntimeError: Failed to generate 'cg_sh010' project! Exited with return code 1
```
</details>

2023-02-22 10:10 UTC, simonebarbieri approved these changes

2023-02-24 14:27 UTC, antirotor approved these changes

2023-02-24 14:31 UTC, merged