scene length setting referenced from DB record for 3dsMax
ynput/OpenPype pull request #4665
Opened 2023-03-21 09:52 UTC by moonyuet

## Changelog Description
 Setting the timeline length based on DB record in 3dsMax Hosts
![image](https://user-images.githubusercontent.com/64118225/226571059-4ef7d1c7-ecc7-448c-a0d1-aa97f1159810.png)

## Additional info
N/A

## Testing notes:
1. launch 3dsMax via Openpype
2. create new scene
3. check the timeline
4. locate "Set Frame Range" in openpype menu
5. click it
6. check the frame range or the timeline to see if it is same with the setting shown in DB

2023-03-21 09:55 UTC, BigRoy commented
This PR seems to also include #4652 - is that correct?

2023-03-21 09:57 UTC, moonyuet commented
> This PR seems to also include #4652 - is that correct?

yes, but they are in a separate ticket, I will wait the old one to merge and update this ticket.  I convert this to draft first

2023-03-21 15:39 UTC, LiborBatek approved these changes
All works as expected! Did several tests in multiple shots and all being ok.

![image](https://user-images.githubusercontent.com/112623825/226659319-73f3cfae-6126-421a-bd80-924684ef688d.png)

2023-03-22 11:47 UTC, antirotor requested changes
`legacy_io` deprecation notes (similar to #4652)

2023-03-22 11:47 UTC, antirotor commented on openpype/hosts/max/api/lib.py
> +    }
We should stop using `legacy_io`:

```suggestion
def get_frame_range() -> Dict:
    """Get the current assets frame range and handles.
    
    Returns:
    	Dict: with frame start, frame end, handle start, handle end.
    
    """
    # Set frame start/end
    asset = get_current_project_asset()

    frame_start = asset["data"].get("frameStart")
    frame_end = asset["data"].get("frameEnd")
    # Backwards compatibility
    if frame_start is None or frame_end is None:
        frame_start = asset["data"].get("edit_in")
        frame_end = asset["data"].get("edit_out")

    if frame_start is None or frame_end is None:
        return

    handles = asset["data"].get("handles") or 0
    handle_start = asset["data"].get("handleStart")
    if handle_start is None:
        handle_start = handles

    handle_end = asset["data"].get("handleEnd")
    if handle_end is None:
        handle_end = handles

    return {
        "frameStart": frame_start,
        "frameEnd": frame_end,
        "handleStart": handle_start,
        "handleEnd": handle_end
    }
```

2023-03-22 11:47 UTC, antirotor commented on openpype/hosts/max/api/lib.py
> +    rt.execute(frange_cmd)
```suggestion
def reset_frame_range(fps: bool=True):
    """Set frame range to current asset.
    
    	This is part of 3dsmax documentation:

        animationRange: A System Global variable which lets you get and
        	set an Interval value that defines the start and end frames
        	of the Active Time Segment.
        frameRate: A System Global variable which lets you get
        	and set an Integer value that defines the current
        	scene frame rate in frames-per-second.
    """
    if fps:
        fps_number = float(get_current_project(fields=["data.fps"])["data"]["fps"])
        rt.frameRate = fps_number

    frame_range = get_frame_range()

    frame_start = frame_range["frameStart"] - int(frame_range["handleStart"])
    frame_end = frame_range["frameEnd"] + int(frame_range["handleEnd"])

    frange_cmd = f"animationRange = interval {frame_start} {frame_end}"

    rt.execute(frange_cmd)
```

2023-03-22 11:47 UTC, antirotor commented on openpype/hosts/max/api/lib.py
> +def reset_scene_resolution():
Please see notes on #4652

2023-03-22 11:47 UTC, antirotor commented on openpype/hosts/max/api/lib.py
> +def set_scene_resolution(width, height):
```suggestion
def set_scene_resolution(width: int, height: int):
```

2023-03-27 14:44 UTC, antirotor approved these changes

2023-03-27 14:44 UTC, merged