Nuke: publisher is offering review on write families on demand
ynput/OpenPype pull request #4755
Opened 2023-03-30 15:45 UTC by jakubjezek001

## Changelog Description
Original idea where reviewable toggle will be offered in publisher on demand is fixed and now `review` attribute can be disabled in settings.

## Additional info
Removed duplicity in class functions. `get_instance_attr_defs` didn't need to be overridden with child instance. 

## Testing notes:
1. go to your testing project studio settings `project_settings/nuke/create/CreateWritePrerender/instance_attributes` and remove `reviwable`. Save settings 
2. Open nuke at testing project workfile
3. open Publisher and create Prerender node
4. Notice that `Review` instance attribute is not shown

2023-03-31 08:26 UTC, iLLiCiTiT commented
Not sure how much of instances are already in scenes but you should probably check if there is `"review"` in collected instances and remove the value if should not be there.

2023-03-31 08:53 UTC, iLLiCiTiT commented
Unrelated to this PR but I got this error on create:
```
Traceback (most recent call last):
  File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\openpype\pipeline\create\context.py", line 1989, in _create_with_unified_error
    result = creator.create(*args, **kwargs)
  File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\openpype\hosts\nuke\plugins\create\create_write_image.py", line 118, in create
    instance_data,
  File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\openpype\hosts\nuke\plugins\create\create_write_image.py", line 86, in create_instance_node
    "frame": nuke.frame()
  File "C:\Users\JakubTrllo\Desktop\Prace\openpype3_2\openpype\hosts\nuke\api\lib.py", line 1288, in create_write_node
    for knob in imageio_writes["knobs"]:
TypeError: 'NoneType' object is not subscriptable
```

2023-03-31 08:57 UTC, iLLiCiTiT requested changes
Linking issue description https://github.com/ynput/OpenPype/pull/4755#issuecomment-1491521288

Collection phase should remove creator attributes that are not valid by settings.

![image](https://user-images.githubusercontent.com/43494761/229074823-d5191b3b-ae68-4c41-8870-a67e9a759cd1.png)

2023-04-05 12:27 UTC, 64qam approved these changes

2023-04-05 12:32 UTC, iLLiCiTiT approved these changes

2023-04-05 12:49 UTC, merged