Maya: Hide animation instance in creator
ynput/OpenPype pull request #4872
Opened 2023-04-19 16:06 UTC by BigRoy

## Changelog Description

- Hide animation instance in creator
- Add inventory action to recreate animation publish instance for loaded rigs

## Additional info

The animation family was often 'misused' by new users as a pointcache output but was originally designed for rigs only. This hides the animation instance but preserves the rig -> animation instance behavior.

It also adds an inventory action to recreate the animation instance if it was accidentally deleted.

![afbeelding](https://user-images.githubusercontent.com/2439881/233134745-9e70f191-6227-4df9-a303-fb8267b71436.png)

## Testing notes:

1. Load a rig - animation instance should be created
2. Recreate animation instance through scene inventory / manager actions.

2023-04-19 16:13 UTC, mkolar commented
I like this! can't test right now, but it's a good idea

2023-04-20 07:13 UTC, tokejepsen requested changes
Tested in Maya 2023 and code looks good.

Could we get some documentation as well?

2023-04-20 14:07 UTC, tokejepsen approved these changes
Great stuff!

2023-04-20 14:29 UTC, antirotor approved these changes

2023-04-20 14:29 UTC, merged