Maya Load References - Add Display Handle Setting
ynput/OpenPype pull request #4904
Opened 2023-04-25 15:01 UTC by mre7a

## Changelog Description
When we load a reference in Maya using OpenPype loader, display handle is checked by default and prevent us to select easily the object in the viewport. 
![image](https://user-images.githubusercontent.com/68907585/234317963-09b1d537-43a5-4715-bf3f-8cd8cc4568e1.png)

I understand that some productions like to keep this option, so I propose to add display handle to the reference loader settings. 
![image](https://user-images.githubusercontent.com/68907585/234317353-e05678a8-e297-4f12-9234-46c4de781542.png)

## Testing notes:
1. Using Openpype loader in Maya, load an asset as reference. 
2. Verify that Display Handle is following the settings.

2023-04-26 07:54 UTC, tokejepsen requested changes
Great work!

Just need those Hound fixes and we can merge.

2023-04-26 07:55 UTC, tokejepsen commented
> I'm wondering whether we should maybe also add the option to allow enabling/disabling it for certain families/profiles? We mostly disabled it because we really didn't like it on e.g. rigs but did like it on some others. Nevertheless we still ended up disabling it completely just it because was much simpler at the time.

Not sure we need that right now unless you need it?
If someone wants it, they can implement profiles later.

2023-04-26 08:14 UTC, mre7a commented
Thanks a lot. 

> Just need those Hound fixes
> Would need some cosmetics cleanup

Oops. Sorry.  vscode issues :)

2023-04-26 08:17 UTC, tokejepsen commented on openpype/hosts/maya/plugins/load/load_reference.py
> +
```suggestion

                display_handle = settings['maya']['load'].get(
                    'reference_loader', {}
                ).get('display_handle', True)
                cmds.setAttr(
                    "{}.displayHandle".format(group_name), display_handle
                )

```

2023-04-26 08:17 UTC, tokejepsen commented on openpype/hosts/maya/plugins/load/load_reference.py
> +                    "{}.displayHandle".format(group_name), display_handle)
```suggestion
                cmds.setAttr(
                    "{}.displayHandle".format(group_name), display_handle
                )
```

2023-04-26 08:24 UTC, antirotor approved these changes

2023-04-26 08:56 UTC, BigRoy approved these changes
Great work, looks good to me.

2023-05-03 06:53 UTC, ClementHector commented
Is there something missing to be adopted?

2023-05-03 09:52 UTC, antirotor approved these changes
Looks great!

2023-05-03 09:52 UTC, merged