Global: collect frames to fix with settings
ynput/OpenPype pull request #5036
Opened 2023-05-25 15:46 UTC by jakubjezek001

## Changelog Description
Settings for `Collect Frames to Fix` will allow disable per project the plugin but also disable attribute for Rewriting version.

## Testing notes:
1. Open settings in `project_settings/global/publish/CollectFramesFixDef/enabled`
2. Open Nuke or Maya and test all settings options in publisher and reload after each change.

2023-05-25 16:04 UTC, m-u-r-p-h-y requested changes
the default setting should be False (Off)

2023-05-25 16:07 UTC, jakubjezek001 commented
> the default setting should be False (Off)

This way it is backward compatible. Before it was always Enabled.

2023-05-25 16:20 UTC, m-u-r-p-h-y commented
> > the default setting should be False (Off)
> 
> This way it is backward compatible. Before it was always Enabled.

so in Nuke you were always overwriting latest version? Sounds weird . . .

2023-05-25 19:37 UTC, jakubjezek001 commented
> ![image](https://user-images.githubusercontent.com/352795/240975659-55f889e7-f0e4-4d33-989a-3a23d91f3f6f.png)
> 
> Nuke render instance is not following the settings

This is expected behavior. It will make the toggle disappear if you disable it in the settings. But I agree I should change the settings label to make it more clear.

2023-05-26 14:09 UTC, m-u-r-p-h-y reviewed
Usual combinations work as expected, just this one with the whole creator disabled, should not propagate the children's state probably . . .

![image](https://github.com/ynput/OpenPype/assets/352795/bcaf0463-e5cf-4887-9131-6c89c95f7416)

2023-05-30 14:53 UTC, jakubjezek001 commented
> Usual combinations work as expected, just this one with the whole creator disabled, should not propagate the children's state probably . . .

After several tests on several computers this was replicated only once and was caused due switching branches with ongoing nuke session.

2023-05-30 14:54 UTC, merged

2023-05-30 15:14 UTC, jakubjezek001 commented on openpype/plugins/publish/collect_frames_fix.py
>          rewrite_version = attribute_values.get("rewrite_version")
fixed in https://github.com/ynput/OpenPype/pull/5064