Openpype settings project global
ynput/OpenPype pull request #5134
Opened 2023-06-13 12:15 UTC by SherineKB

## Changelog Description
Update of the Project Global settings : 
Re-organized the page, added the missing categories of the panel and completed their informations.

2023-06-13 12:27 UTC, BigRoy commented on website/docs/admin_settings_local.md
> +Futur version of existing tools or new ones.
```suggestion
Future version of existing tools or new ones.
```

2023-06-13 12:27 UTC, BigRoy commented on website/docs/admin_settings_local.md
> +**OpenPype Username** : enter your username (it can also take by default the computer session username). It signs your actions on **OpenPype**.
Admittedly this is unclear to me. How does it sign my actions on OpenPype? What does that influence?

Here is it a bit tweaked. Note that I'm not sure if my example is actually correct and whether it does that.

```suggestion
**OpenPype Username** : enter your username (if not provided, it uses computer session username by default). This username is used to sign your actions on **OpenPype**, for example the "author" on a publish.
```

2023-06-13 12:27 UTC, BigRoy commented on website/docs/admin_settings_local.md
> +**Admin permissions** : on checked, no need to enter a password (if defined) to access to the **Admin** section.
```suggestion
**Admin permissions** : When enabled you do not need to enter a password (if defined in Studio Settings) to access to the **Admin** section.
```

2023-06-13 12:27 UTC, BigRoy commented on website/docs/admin_settings_local.md
> +Local override of software paths and their versions. More details [here](admin_settings_system.md#applications).
```suggestion
Local override of software executable paths for each version. More details [here](admin_settings_system.md#applications).
```

2023-06-16 15:09 UTC, ClementHector requested changes

2023-06-20 11:36 UTC, closed without merging