Maya: Fix collecting arnold prefix when none
ynput/OpenPype pull request #5243
Opened 2023-07-05 08:19 UTC by tokejepsen

## Changelog Description
When no prefix is specified in render settings, the renderlayer collector would error.

## Testing notes:
1. Setup `render` in Maya.
2. Ensure no prefix is specified in render settings.
3. Publish and verify no errors occur.

2023-07-05 10:36 UTC, BigRoy commented
Actually, this error is not arnold-specific. I've recently fixed the same on our end but did so [here](https://github.com/ynput/OpenPype/blob/2188a8a975072a0c966e893828ed09b4836e2566/openpype/hosts/maya/api/lib_renderproducts.py#L281-L284).

There was already logic there but it was using the wrong variable name. See [this commit](https://github.com/ynput/OpenPype/commit/2188a8a975072a0c966e893828ed09b4836e2566).

2023-07-05 11:16 UTC, LiborBatek requested changes
I have set the testing conditions (without prefix touched) I have also created the ```Render``` instance before loading MtoA (otherwise prefixes get prefilled during creation of Render Instance).

![image](https://github.com/ynput/OpenPype/assets/112623825/17fa1303-ec63-47b9-9dac-79efdac4917f)


But getting validation errors still (regarding Image Prefix)

![image](https://github.com/ynput/OpenPype/assets/112623825/e585eefe-e216-4b18-b7d8-d48fed5bf428)

2023-07-05 11:20 UTC, tokejepsen commented
@LiborBatek validation errors are not part of this PR. Should be able to repair them anyways.

2023-07-05 11:36 UTC, BigRoy commented
@tokejepsen How do you feel about aligning this PR with the fix in [the commit](https://github.com/ynput/OpenPype/commit/2188a8a975072a0c966e893828ed09b4836e2566) I mentioned [here](https://github.com/ynput/OpenPype/pull/5243#issuecomment-1621491909)?

2023-07-05 11:42 UTC, tokejepsen commented
> @tokejepsen How do you feel about aligning this PR with the fix in [the commit](https://github.com/ynput/OpenPype/commit/2188a8a975072a0c966e893828ed09b4836e2566) I mentioned [here](https://github.com/ynput/OpenPype/pull/5243#issuecomment-1621491909)?

Sounds good

2023-07-05 11:50 UTC, LiborBatek commented
> @LiborBatek validation errors are not part of this PR. Should be able to repair them anyways.

Then update testing steps pls ....be more specific in testing steps....should I Repair then the missing Image Prefixes or not??

Its pretty vaque and unclear to me.

2023-07-05 11:55 UTC, tokejepsen commented
> > @LiborBatek validation errors are not part of this PR. Should be able to repair them anyways.
> 
> Then update testing steps pls ....be more specific in testing steps....should I Repair then the missing Image Prefixes or not??
> 
> Its pretty vaque and unclear to me.

Sure, have updated the testing steps now

2023-07-06 09:27 UTC, LiborBatek approved these changes
There are no errors shown during Collecting phase.

![image](https://github.com/ynput/OpenPype/assets/112623825/c27edbd6-c73a-42ff-b943-b0a2ae0ed0e5)

2023-07-06 10:01 UTC, merged