Autosave preferences can be read after Nuke opens the script
ynput/OpenPype pull request #5295
Opened 2023-07-13 13:56 UTC by jrsndl

## Changelog Description
Looks like I need to open the script in Nuke to be able to correctly load the autosave preferences.
This PR reads the Nuke script in context, and offers owerwriting the current script with autosaved one if autosave exists.

## Testing notes:
1. Launch Nuke via Openpype
2. Go to Openpype menu and click work file
3. Open any nuke script with autosave
4. It will pop up nuke prompt to ask if you want to open autosave script.
5. It will load autosave script for you if you click yes; while it wont if you click no.

Also try to change autosave location in Nuke prefs to some random place, wait till autosave kicks in and kill Nuke.
OP should detect and offer autosaves that is not located next to the workfile as well.

2023-07-19 09:04 UTC, 64qam commented
I think this has been resolved here https://github.com/ynput/OpenPype/pull/5107

2023-07-31 14:12 UTC, jakubjezek001 requested changes
Need to fix the nuke version condition to be from `14` perhaps?

2023-08-04 13:09 UTC, jrsndl commented on openpype/hosts/nuke/api/workio.py
> +        if int(nuke.NUKE_VERSION_MAJOR) > 12:
I didn't test with Nuke 13.x.
I just noticed that in Nuke 12, using nuke.scriptReadFile causes Nuke to "not know the nuke.root.name", but using nuke.scriptOpen is fine.

Maybe the error you are getting would happen anytime you open script from Higher version?

I will test Nuke 13

2023-08-04 13:16 UTC, jrsndl commented
I 've removed the Nuke 12 compatibility condition for now. It is too old anyway.

2023-08-07 12:50 UTC, jakubjezek001 approved these changes

2023-08-07 12:54 UTC, merged