Copy publish attributes from review instance to any attached instances
ynput/OpenPype pull request #5296
Opened 2023-07-13 13:59 UTC by mkolar

## Changelog Description
Fixes situation where frame range validator can't be turned off on models if they are attached to reviewable camera in Maya. 

## Testing notes:
1. Create model publish instance in maya
2. create review publish instance in maya 
3. parent model maya set under the review maya set based on this **https://ayon.ynput.io/docs/artist_hosts_maya#publishing-model-with-review**
4. turn off `validate frame range` on the review in the publisher GUI. 
5. Everything should go through correctly and you should end up with review attached to the model Product.

2023-07-14 07:25 UTC, tokejepsen requested changes
I'm getting validation passed with the `Validate Frame Range` enabled as well as disabled.

![cap1](https://github.com/ynput/OpenPype/assets/1860085/8e7d35ae-6208-41f3-bd70-ac3c28b20b04)
![cap2](https://github.com/ynput/OpenPype/assets/1860085/2974dcb1-6369-48a7-83c0-0edf35352d95)

2023-07-14 08:25 UTC, LiborBatek reviewed
Strangely it works no matter if ```Validate Frame Range``` being ```ON``` or ```OFF```  even when asset DB ```frame range```  ```1001-1001``` and review differ by ```1001-1050```

![image](https://github.com/ynput/OpenPype/assets/112623825/45dd0ffa-4e89-4117-8021-44f704dff8cc)

2023-07-22 09:23 UTC, tokejepsen commented
For testing this we also need to remove the `model` family from `project_settings/maya/publish/ValidateFrameRange/exclude_families`, which is quite confusing given the label of the settings as well.

I've suggested a code fix for this PR [here](https://github.com/ynput/OpenPype/pull/5340)

2023-07-27 07:39 UTC, tokejepsen approved these changes
Tested in Maya 2023 successfully. Code looks good to me as well.

2023-07-27 20:56 UTC, merged