Feature/fusion resolution validator
ynput/OpenPype pull request #5325
Opened 2023-07-20 13:48 UTC by EmberLightVFX

## Changelog Description
Added a resolution validator.
The code is from my old PR (https://github.com/ynput/OpenPype/pull/4921) that I closed because the PR also contained a frame range validator that no longer is needed.

## Additional info
The validator is optional as you might want/need to render out different resolutions than what's set for the asset.

## Testing notes:
1. Make a BG node with a different resolution than your asset
2. Create a new saver and pipe in the BG
3. Validate and see an error pop up

2023-09-04 14:30 UTC, BigRoy commented on openpype/hosts/fusion/plugins/publish/validator_saver_resolution.py
> +        """Validate if the saver rescive the expected resolution"""
rescive?

```suggestion
        """Validate if the saver receives the expected resolution"""
```

2023-09-04 14:31 UTC, BigRoy commented on openpype/hosts/fusion/plugins/publish/validator_saver_resolution.py
> +        # the comments field to read the resolution
```suggestion
        # If the current saver hasn't been rendered its input resolution
        # hasn't been saved. To combat this, add an expression in
        # the comments field to read the resolution
```

2023-09-04 14:33 UTC, jakubjezek001 commented on openpype/hosts/fusion/plugins/publish/validator_saver_resolution.py
> +        saver = instance[0]
```suggestion
        saver = instance.data["tool"]
```

2023-09-04 14:35 UTC, jakubjezek001 requested changes
Thanks for contribution @EmberLightVFX. Please address the fixes and then it is good to be merged.

2023-09-04 14:35 UTC, jakubjezek001 commented on openpype/hosts/fusion/plugins/publish/validator_saver_resolution.py
> +        saver = instance[0]
There is not a tool in the list position anymore.

2023-10-02 12:20 UTC, BigRoy approved these changes
Works as intended.

![image](https://github.com/ynput/OpenPype/assets/2439881/12d97142-ddfa-4b69-a470-e71647f58528)

Only doubt I have is maybe the label on the validator - would it make sense to label that "Validate Asset Resolution" instead of "Validate Saver Resolution" since it might make more sense to the artist what it is being validated against?

![image](https://github.com/ynput/OpenPype/assets/2439881/3e9cc5be-191e-4864-a251-b3cb88d0e306)

2023-10-02 12:21 UTC, BigRoy commented on openpype/hosts/fusion/plugins/publish/validate_saver_resolution.py
> +    label = "Validate Saver Resolution"
```suggestion
    label = "Validate Asset Resolution"
```

2023-10-30 11:21 UTC, jakubjezek001 approved these changes
LGTM. Thank you!

2023-10-30 11:22 UTC, merged

2023-10-30 11:24 UTC, BigRoy commented
@jakubjezek001 ⚠️ This PR is lacking matching settings for AYON so a fix PR to create the missing Fusion settings for AYON should be generated.