Chore: Default variant in create plugin
ynput/OpenPype pull request #5429
Opened 2023-08-08 14:43 UTC by iLLiCiTiT

## Changelog Description
Attribute `default_variant` on create plugins always returns string and if default variant is not filled other ways how to get one are implemented.

## Additional info
Renamed `default_variant` to `_default_variant`, and make `default_variant` as property. The property has getter, and setter for auto settings apply, the property is calling `get_default_variant` method inside. Method `get_default_variant` uses `_default_variant` if is available, otherwise uses first available value from `default_variants`, or new conststant `DEFAULT_VARIANT_VALUE` if even they are not available.

Added auto-fix of `default_variant` property if a plugin did overide it.

## Testing notes:
- Visually nothing should change.
- All plugins should work as expected, and their settings should be propagated.

2023-08-08 15:15 UTC, iLLiCiTiT commented on openpype/pipeline/create/creator_plugins.py
> +                variant from '_default_variant' will be returned.
Debug (I've used it for testing of this PR).

2023-08-08 18:03 UTC, fabiaserra commented on openpype/pipeline/create/creator_plugins.py
Typo on docstring:
```
        Replacement of `defaults` attribute. Using method gives ability to
```

2023-08-10 09:58 UTC, kalisp requested changes
I would expect to see `Default` in `Variant` field:
![AnyDeskMSI_qv25KsFUmY](https://github.com/ynput/OpenPype/assets/4457962/0d2f680f-6b3d-458a-87fd-ad693d89997d)

2023-08-11 12:34 UTC, iLLiCiTiT commented on openpype/pipeline/create/constants.py
> +DEFAULT_VARIANT_VALUE = "main"
```suggestion
DEFAULT_VARIANT_VALUE = "Main"
```

2023-08-15 11:36 UTC, merged