Unreal: Fix Layout missing support for staticMesh and skeletalMesh families
ynput/OpenPype pull request #5628
Opened 2023-09-18 12:01 UTC by simonebarbieri

## Changelog Description
Fix missing support for `staticMesh` and `skeletalMesh` families in layouts.

## Testing notes:
1. Publish from Maya a layout that includes `staticMesh` and/or `skeletalMesh` assets.
2. Try loading it in Unreal.

2023-09-19 12:57 UTC, LiborBatek requested changes
When including ```skeletalMesh``` in ```maya``` and ```layout``` it loads into ```UE``` without fails but it misses the actual asset.
Here in ```maya```
![image](https://github.com/ynput/OpenPype/assets/112623825/76464d4e-9ecd-4ee6-928a-04eac4b2d13b)

and in UE:
![image](https://github.com/ynput/OpenPype/assets/112623825/f36e0621-d455-49d0-b48d-5619bb011d00)

It is not present in the loaded ```Layout``` but at least imported as UAsset (as seen in the Content Browser)

Also tried to use ```Load Layout on existing``` after first ```Load Layout``` being not successful but without any advance, asset still
being missing.

2024-08-14 16:40 UTC, dee-ynput commented
@antirotor @moonyuet 
Is this still relevant? should we move it to Unreal repo?

2024-08-16 12:46 UTC, moonyuet commented
> @antirotor @moonyuet Is this still relevant? should we move it to Unreal repo?

I believe it is already moved to the repo. https://github.com/ynput/ayon-unreal/pull/10

2024-08-20 07:23 UTC, LiborBatek commented
Can be closed in a favour of this [PR](https://github.com/ynput/ayon-unreal/pull/10) in ayon-unreal ...

2024-08-20 07:23 UTC, closed without merging