Unreal : Parent Qt UI to Windows main Unreal
ynput/OpenPype pull request #5656
Opened 2023-09-27 08:33 UTC by sebasti1a

## Changelog Description
Improved Qt window parenting for Unreal window. I disabled the setWindowFlags : WindowStaysOnTopHint and I use this function : unreal.parent_external_window_to_slate

## Additional info
Test with Unreal 5.3

## Testing notes:
1. Open Unreal
2. Click on Ayon Menu
3. The popup UI is now correctly parent with unreal

2023-09-29 09:21 UTC, simonebarbieri commented
Hello. I'm not entirely sure about the purpose of this PR. The current window is made to behave like a dropdown menu, but we have a dialog accessible from the Tools menu that already behaves like this PR!
![image](https://github.com/ynput/OpenPype/assets/1087869/0155ce3c-6827-4a80-955d-ae84fef640b1)

2023-09-29 09:42 UTC, sebasti1a commented
Actually, It's the Qt window that is not correctly linked to the Unreal application, for example when I minimize Unreal, the Ayon tools window still remains visible in WindowStaysOnTop. My PR fixes that.

![image](https://github.com/ynput/OpenPype/assets/89812691/f7a582df-b3b3-41d8-a410-a7aecc0a495c)

2023-09-29 10:31 UTC, simonebarbieri commented
Ah, in that case, that works, but I think that the menu should still behave as a dropdown menu and disappear when out of focus :)
Now the two options (popup and dialog) behaves the same, at least with Unreal 5.2! Haven't tested 5.3.

2023-09-29 13:35 UTC, sebasti1a commented
I tested with Unreal 5.3 and "AyonTools" is still a drop-down menu (the window is not persistent and disappear when out of focus ). Like expected behavior.

2023-10-31 11:39 UTC, antirotor requested changes
Strange thing is that my  UE 5.3 is actually showing this:

![op_ue_ayontools_qt_01 gif](https://github.com/ynput/OpenPype/assets/33513211/6aec2e46-d347-4f55-97a6-f7c24a3577f6)

Could it be because of the Qt version? Mine is:

![image](https://github.com/ynput/OpenPype/assets/33513211/b7bf8639-8407-442b-b055-6ded7154e48c)

2024-02-06 22:25 UTC, mkolar commented
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be re-created to target one of those. 

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-unreal](https://github.com/ynput/ayon-unreal) repository once it's up.

2024-02-06 22:25 UTC, closed without merging