Maya: Add Maya 2024 and remove pre 2022.
ynput/OpenPype pull request #5674
Opened 2023-10-02 15:31 UTC by tokejepsen

## Changelog Description
Adding Maya 2024 as default application variant.

Removing Maya 2020 and older, as these are not supported anymore.

## Testing notes:
1. Launch settings with a new database and validate only Maya 2024-2022 is present.

Split from https://github.com/ynput/OpenPype/pull/5644

2023-10-02 15:37 UTC, BigRoy approved these changes
Didn't test but looks good to me ❤️

2023-10-02 15:38 UTC, BigRoy commented
Actually - is this missing an update to AYON settings for Maya?

2023-10-02 16:17 UTC, iLLiCiTiT commented
Please add AYON settings changes too.

2023-10-02 18:24 UTC, BigRoy requested changes
As stated - this should also update AYON defaults.
_Sorry for commenting the same thing - I had to place a comment to change my approval status_

2023-10-03 07:51 UTC, BigRoy approved these changes
Didn't test it - but code looks good. Probably best to check against new deployment of Ayon and OpenPype I suppose? Probably for @LiborBatek?

2023-10-05 10:23 UTC, Minkiu approved these changes

2023-10-05 10:54 UTC, iLLiCiTiT approved these changes
Code changes look ok. Someone has to validate if we should limit the maya versions to this set. @m-u-r-p-h-y ?

2023-10-05 11:02 UTC, antirotor approved these changes

2023-10-05 11:04 UTC, antirotor commented
> Code changes look ok. Someone has to validate if we should limit the maya versions to this set. @m-u-r-p-h-y ?

I don't think we support Maya 2018 and with Maya 2020 I would be surprised if there are no issues. Anyway, there's no problem to  define them locally if needed

2023-10-05 11:42 UTC, m-u-r-p-h-y commented
I agree to have only M2021 and up

if we are touching the defaults I would like to unify the paths for other platforms. We have linux paths defined somewhere but no Mac (not sure what is the default path on MAc though)

something like `/Applications/Autodesk/maya2021/Maya.app/Contents/bin/maya` ?

2023-10-05 11:47 UTC, tokejepsen commented
> if we are touching the defaults I would like to unify the paths for other platforms. We have linux paths defined somewhere but no Mac (not sure what is the default path on MAc though)

Could this be a different PR for another time?

2023-10-17 06:18 UTC, mkolar commented
I agree we can tweak the paths in another PR. let's merge this, so it's not festering.

2023-10-17 06:19 UTC, merged