Nuke: ayon server settings improvements
ynput/OpenPype pull request #5746
Opened 2023-10-11 13:28 UTC by jakubjezek001

## Changelog Description
Nuke settings were not aligned with OpenPype settings. Also labels needed to be improved.

## Additional info
- imroving consistency of key names

## Testing notes:
1. all should be working as it was before
2. create preset in `ayon+settings://nuke:0.1.4/imageio/nodes/override_nodes?project=SyncSketchTesting` and notice there is `Subsets` input

2023-10-11 14:40 UTC, moonyuet approved these changes
LGTM

2023-10-11 15:18 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +    if ayon_imageio_nodes.get("required_nodes"):
```suggestion
    if "required_nodes" in ayon_imageio_nodes:
```

2023-10-11 15:18 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +    if ayon_imageio_nodes.get("override_nodes"):
```suggestion
    if "override_nodes" in ayon_imageio_nodes:
```

2023-10-11 15:19 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +            item["nukeNodeClass"] = item["nuke_node_class"]
```suggestion
        if "nuke_node_class" in item:
            item["nukeNodeClass"] = item.pop("nuke_node_class")
```

2023-10-11 15:19 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +            item["nukeNodeClass"] = item["nuke_node_class"]
```suggestion
        if "nuke_node_class" in item:
            item["nukeNodeClass"] = item.pop("nuke_node_class")
```

2023-10-11 15:19 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +    if ayon_imageio_nodes.get("override_nodes"):
```suggestion
    if "override_nodes" in ayon_imageio_nodes:
```

2023-10-11 15:20 UTC, iLLiCiTiT commented on openpype/settings/ayon_settings.py
> +        ayon_imageio["regexInputs"] = regex_inputs
```suggestion
    if "regex_inputs" in ayon_imageio:
        ayon_imageio["regexInputs"] = ayon_imageio.pop("regex_inputs")
```

2023-10-18 10:38 UTC, iLLiCiTiT requested changes
Please look at the suggestions.

2023-10-18 12:07 UTC, jakubjezek001 commented on openpype/settings/ayon_settings.py
> +    if ayon_imageio_nodes.get("override_nodes"):
implemented

2023-10-18 12:09 UTC, jakubjezek001 commented
@iLLiCiTiT all of your suggestions were committed, thanks to them ;)

2023-10-18 12:13 UTC, iLLiCiTiT approved these changes
Looks good.

2023-10-19 12:50 UTC, 64qam approved these changes

2023-10-19 12:50 UTC, 64qam approved these changes

2023-10-25 22:24 UTC, merged