Maya: Repair task in instance in context.
ynput/OpenPype pull request #5912
Opened 2023-11-14 09:38 UTC by tokejepsen

## Changelog Description
When repairing the instance in context, only the asset gets repaired, but this can lead to a confusing situation where the publisher blocks validation and publishing due to the task being invalid.

![instance_in_context_task](https://github.com/ynput/OpenPype/assets/1860085/bc6a5b36-dfe8-4715-a658-21c6ea6c2bef)

## Testing notes:
1. Open a workfile with existing instances and save to a different context.
2. Publish the instances and repair the `instance in context` validation.

2023-11-14 09:54 UTC, BigRoy commented
@tokejepsen Makes sense - however, you should also fix up the validation itself - this currently won't detect context mismatches if you only saved to a different task within the same asset instead of different asset. Correct?

2023-11-14 12:16 UTC, tokejepsen commented
@BigRoy good point! Have adjusted the PR now.

2023-11-14 13:00 UTC, BigRoy commented
> Open a workfile with existing instances and save to a different context.

Also @tokejepsen I believe there's actually built-in logic that updates the instances on context change as well - making the validator usually quite irrelevant.

The call to that is [here](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/pipeline.py#L657-L659)
With as you can see [here](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/lib.py#L3225-L3249) updating the asset to the new context.

Looking at that now _that_ should also be fixed and _that_ should also be updating `task` then.

2023-11-14 13:02 UTC, tokejepsen commented
> Looking at that now that should also be fixed and that should also be updating task then.

We have some Maya scene publishing etc where this logic does not work, so I would rather have this back stopper to catch all edge cases.

2023-11-14 13:20 UTC, BigRoy commented
> We have some Maya scene publishing etc where this logic does not work, so I would rather have this back stopper to catch all edge cases.

Fine with me - but could we patch up that 'bug' as well? Just so the gaps are filled. 

The validator still existing is fine with me, there are cases where the context change can't be captured (e.g. someone copy pasting a scene outside of maya).

2023-11-14 13:30 UTC, iLLiCiTiT commented on openpype/hosts/maya/plugins/publish/validate_instance_in_context.py
> +        if asset != instance.context.data["assetEntity"]["name"]:
```suggestion
        if asset != instance.context.data["asset"]:
```

2023-11-15 07:58 UTC, moonyuet reviewed
The validation successfully repair the context data. 
![image](https://github.com/ynput/OpenPype/assets/64118225/d090b2ef-8c2e-4ddb-b15f-613dbadd0965)
But I have one question to the PR, I create the instance with the variant name such as `abc` and the subset name also named with the variant. But if I changed the variant name, validation fails and fix the context data, but the name of the set which stores the publishing data is still with the original name(you can see the screenshot above). Is it expected behavior?

2023-11-15 08:20 UTC, BigRoy commented
> But if I changed the variant name, validation fails and fix the context data, but the name of the set which stores the publishing data is still with the original name(you can see the screenshot above). Is it expected behavior?

Whether it's 'expected' for artists, likely not, but I believe it's always been like that so far. :) It's unrelated to this PR however.

2023-11-15 08:44 UTC, moonyuet approved these changes

2023-11-15 09:52 UTC, BigRoy requested changes
> > Open a workfile with existing instances and save to a different context.
> 
> Also @tokejepsen I believe there's actually built-in logic that updates the instances on context change as well - making the validator usually quite irrelevant.
> 
> The call to that is [here](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/pipeline.py#L657-L659) With as you can see [here](https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/maya/api/lib.py#L3225-L3249) updating the asset to the new context.
> 
> Looking at that now _that_ should also be fixed and _that_ should also be updating `task` then.

I believe this should still be added.

2024-02-09 22:33 UTC, mkolar commented
Because we're splitting OpenPype into ayon-core and individual host addons, this PR would have to be ported to target one of those.

We're closing it down, but we'll he happy for a new PR to [ynput/ayon-core](https://github.com/ynput/ayon-core) or the host addon repository once it's up.

2024-02-09 22:33 UTC, closed without merging