Hiero: Effect Categories - OP-7397
ynput/OpenPype pull request #6143
Opened 2024-01-16 17:37 UTC by tokejepsen

## Changelog Description
This PR introduces `Effect Categories` for the Hiero settings. This allows studios to split effect stacks into meaningful subsets.

## Testing notes:
1. Setup `Effect Categories` in Hiero addon settings (see documentation).
2. Setup a clip in Hiero with effects corresponding to the settings.
3. Publish clip and effects.
4. Load into Nuke and verify the effects are grouped correctly.

2024-01-16 17:38 UTC, tokejepsen commented
Docs https://github.com/ynput/ayon-documentation/pull/123

2024-01-18 14:48 UTC, jakubjezek001 requested changes
awesome work! Can we also add default values as you were showing in documentation into the variable `DEFAULT_PUBLISH_PLUGIN_SETTINGS`?

2024-01-22 10:35 UTC, tokejepsen commented
> Can we also add default values as you were showing in documentation into the variable DEFAULT_PUBLISH_PLUGIN_SETTINGS?

I would maybe argue that we should not have any defaults to maintain backwards compatibility?

2024-01-22 11:04 UTC, tokejepsen commented
> It is not collecting soft effect nodes and then those are not serialized into json files.

@jakubjezek001 I'm not entirely sure what you meant here, but I've fixed the case where effects are not categorized, in which case we just dump the effects into the "main" effects.

2024-01-23 13:11 UTC, jakubjezek001 commented on openpype/hosts/hiero/plugins/publish/collect_clip_effects.py
> +                if value["class"].startswith(cls):
```suggestion
                if cls in value["class"]:
```

2024-01-23 13:13 UTC, jakubjezek001 approved these changes
Once the suggestion is implemented anyhow, then it is good for merge.

2024-01-23 16:13 UTC, merged